# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_date', models.DateTimeField()),
                ('tweet_username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Tweets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('friends', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('creation_date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterparser.Tweet')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
